# Minimal config to allow helm template to work for image extraction
# wire-utility chart has fail() checks that require certain values

postgresql:
  secrets:
    name: wire-postgresql-secret # for demo the secret name is `wire-postgresql-secret`
    key: password
cargohold:
  config:
    aws:
      s3Endpoint: "http://fake-aws-s3:9000"
