redis-ephemeral:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 6.2.16
  usePassword: false
  cluster:
    enabled: true
    # https://artifacthub.io/packages/helm/bitnami-aks/redis/11.3.4#production-configuration
    # default slaveCount is 2
    slaveCount: 3
  master:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  slave:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"