---
- name: rabbitmq default file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: etc/default/rabbitmq-server.j2, dest: /etc/default/rabbitmq-server }
    - { src: etc/rabbitmq/rabbitmq.config.j2, dest: /etc/rabbitmq/rabbitmq.config }
    # - { src: etc/rabbitmq/rabbitmq-env.conf.j2, dest: /etc/rabbitmq/rabbitmq-env.conf }
  notify:
    restart rabbitmq-server

- name: restart rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted

- name: Enable the plugins is installed
  command: rabbitmq-plugins enable --offline {{ item }}
  with_items: "{{ rabbitmq_plugins }}"
  register: plugin_result
  changed_when: "'already enabled' not in plugin_result.stdout"
  notify: restart rabbitmq-server

- name: restart rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted
