apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    wireService: proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      wireService: proxy
  template:
    metadata:
      labels:
        wireService: proxy
        release: {{ .Release.Name }}
      annotations:
        # An annotation of the configmap checksum ensures changes to the configmap cause a redeployment upon `helm upgrade`
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: "proxy-config"
          configMap:
            name: "proxy"
        - name: "proxy-secrets"
          secret:
            secretName: "proxy"
      containers:
        - name: proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          volumeMounts:
          - name: "proxy-secrets"
            mountPath: "/etc/wire/proxy/secrets"
          - name: "proxy-config"
            mountPath: "/etc/wire/proxy/conf"
          env:
          {{- if .Values.config.proxy.httpProxy }}
          - name: http_proxy
            value: {{ .Values.config.proxy.httpProxy | quote }}
          - name: HTTP_PROXY
            value: {{ .Values.config.proxy.httpProxy | quote }}
          {{- end }}
          {{- if .Values.config.proxy.httpsProxy }}
          - name: https_proxy
            value: {{ .Values.config.proxy.httpsProxy | quote }}
          - name: HTTPS_PROXY
            value: {{ .Values.config.proxy.httpsProxy | quote }}
          {{- end }}
          {{- if .Values.config.proxy.noProxy }}
          - name: no_proxy
            value: {{ .Values.config.proxy.noProxy | quote }}
          - name: NO_PROXY
            value: {{ .Values.config.proxy.noProxy | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /i/status
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /i/status
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
