apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-index
  labels:
    wireService: elasticsearch-index
    app: elasticsearch-index
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- if .Values.hook.enabled }}
  annotations:
    # when hook.enabled=true (default), this chart does not work standalone, but is intended as
    # either a 'post'-subchart to an elasticsearch chart or a 'pre'-subchart to wire-server
    # For the meaning of hooks, see https://docs.helm.sh/developing_charts/#hooks
    "helm.sh/hook": {{ .Values.hook.type }}-install,{{ .Values.hook.type }}-upgrade
    "helm.sh/hook-weight": "10" # ensure this runs after elasticsearch-index configmap
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        wireService: elasticsearch-index
        app: elasticsearch-index
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: curl
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - create
            - --elasticsearch-server
            - "http://{{ required "missing elasticsearch-index.elasticsearch.host!" .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
            - --elasticsearch-index
            - "{{ .Values.elasticsearch.index }}"
            - --elasticsearch-shards=5
            - --elasticsearch-replicas=2
            - --elasticsearch-refresh-interval=5
