wiab-staging:
  hosts:
    deploy_node:
      ansible_host: example.com
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o TCPKeepAlive=yes'
      ansible_user: 'demo'
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
  vars:
    artifact_hash: 2b117e47a00e0cb6bf72dc629f8c970be1682a76
