# Default values for the team-settings.
replicaCount: 1
resources:
  requests:
    memory: 256Mi
    cpu: "0.5"
  limits:
    memory: 512Mi
    cpu: "1"
image:
  repository: quay.io/wire/account-pages
  tag: 505494f69d957564641300955782c02220d0475a
service:
  https:
    externalPort: 443
  http:
    servicePort: 8080

## The following has to be provided to deploy this chart

#config:
#  externalUrls:
#   backendRest: <nginz-subdomain-https.your.domain>
#   backendDomain: <your.domain>
#   webappHost: <webapp-subdomain-webapp.your.domain>
