# See defaults in https://github.com/kubernetes/charts/blob/master/incubator/cassandra/values.yaml
cassandra-ephemeral:
  image:
    repo: "cassandra"
    tag: "3.11.1"
  persistence:
    enabled: false
  resources:
    requests:
      memory: 2.0Gi
      cpu: 1
    limits:
      memory: 4.0Gi
      cpu: 4
  ## Change cassandra configuration paramaters below:
  ## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html
  ## Recommended max heap size is 1/2 of system memory
  ## Recommeneed heap new size is 1/4 of max heap size
  ## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html
  config:
    cluster_size: 1
    seed_size: 1
    max_heap_size: 2048M
    heap_new_size: 1024M
